pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /tmp/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Archive Artifacts') {
            steps {
                    sh 'tar -czvf my-artifacts.tar.gz -C /tmp/ .'
                }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def customImage = docker.build('simple-maven-app')
                    customImage.inside {
                        sh 'cp -r . /app'
                    }
        }
    }
}

    }
}
